[build]
  base = "frontend"
  command = "CI= npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  CI = "true"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_API_URL = "sua_url_da_api_vercel"

[[plugins]]
  package = "@netlify/plugin-nextjs"
